#!/bin/bash
# SSH Command: eval "$(curl -ks https://gitlab.com/uniqueops/ava/raw/master/ava)";
# Description: This is the launcher for Project: A.V.A
# Contributors: Casey McLaughlin
echo -e "                             ";
echo -e "=============================";
echo -e "     _    __     __    _     ";
echo -e "    / \   \ \   / /   / \    ";
echo -e "   / _ \   \ \ / /   / _ \   ";
echo -e "  / ___ \  _\ V /_  / ___ \  ";
echo -e " /_/   \_\(_)\_/(_)/_/   \_\ ";
echo -e "                             ";
echo -e "=============================";

echo -e "[I] Project: Ava Launcher has been initiated";
echo -e "[I] Version 0.1 is detected";