#!/bin/bash
# SSH Command: eval "$(curl -ks https://raw.githubusercontent.com/UniqueOps/A.V.A/master/ava)";
# Description: This is the launcher for Project: A.V.A
# Contributors: Casey McLaughlin

echo -e "     _    __     __    _     ";
echo -e "    / \   \ \   / /   / \    ";
echo -e "   / _ \   \ \ / /   / _ \   ";
echo -e "  / ___ \  _\ V /_  / ___ \  ";
echo -e " /_/   \_\(_)\_/(_)/_/   \_\ ";
echo -e "=============================";
echo -e "                             ";
echo -e "[--] Project: Ava launcher has been initiated";
echo -e "[--] Version 0.1 of project has been detected\\n";
echo -e "[--] Loading Global Vairables"
eval "$(curl -ks https://raw.githubusercontent.com/UniqueOps/A.V.A/master/var/global 2>/dev/null)"; # Splash of Color
echo -e "$Color_Green[OK]$Color_Reset Global Variables Activated"
global_os=$(uname 2>/dev/null);
if [[ "$global_os" != "Linux2" ]]; then
 echo -e "$Color_Red[!!]$Color_Reset Unsupported Operating System Detected";
 echo -e "[--] Shutting Down";
 exit
fi
echo -e "$Color_Green[OK]$Color_Reset $global_os Operating System Detected";
#echo -e "[--] Detecting 
#source "/etc/*-release";



#echo -e "[--] Loading global vairables"
#echo -e "[--] Loading the table library"
#eval "$(curl -ks https://raw.githubusercontent.com/UniqueOps/A.V.A/master/sys/tables2)"; # Splash of Color
#echo -e "$Color_Green[OK]$Color_Reset Table library has been successfully loaded"
#echo -e "[--] Begining troubleshoot and analysis workflow\\n"













#echo -e "Output Options:";
#echo -e "- Verbose: Standard script output";
#echo -e "- Silent: Standard script output but minimized where possible";
#echo -e "- Ticket: Will display the Silent output mode and at the end make a ticket formatted section\\n"

#PS3='Which output would you like: '
#options=("Verbose" "Silent" "Ticket" "Quit")
#select opt in "${options[@]}"
#do
#    case $opt in
#        "Verbose")
#            bash <(curl -ks https://raw.githubusercontent.com/UniqueOps/A.V.A/master/mod/quickinfo) -o
#            ;;
#        "Silent")
#            echo "you chose choice 2"
#            ;;
#        "Ticket")
#            echo "you chose choice 3"
#            ;;
#        "Quit")
#            break
#            ;;
#        *) echo invalid option;;
#    esac
#done
#echo -e "";
