#!/bin/bash
# Description: Global Variables
# Contributors: Casey McLaughlin

eval "$(curl -k -s https://gitlab.com/uniqueops/ava/raw/master/var/colors)"                             # Add Color

# Basic Server Information
readonly Core_Server_Hostname=$(hostname);
readonly Core_Server_IP=$(hostname -i);
readonly Core_Server_Processors=$(nproc);
readonly Core_Server_Uptime=$(uptime | awk '{print $3,$4}' | tr ',' ' ');
#Core_Server_OS=$(lsb_release -a | awk 'FNR==3 {$1=""; $6=""; print}' | tr 'C' 'C'); #Not Working

function Global_Nameserver_Check() {                                                                    # Generate Nameserver Check Row
  Global_Nameserver_Check_Status="$STATUS_FAIL"                                                         # Set Status For Nameserver Check
  Global_Nameserver_Check_Info=$(dig ns +short "$domain" | sort | sed -e :a -e '$!N; s/\n/ | /; ta');   # Grab Nameservers For Domain
  if [ -n "$Global_Nameserver_Check_Info" ]; then
    new_row "$STATUS_INFO" "Global Nameservers: $Global_Nameserver_Check_Info"
    new_row "$STATUS_PASS" "Parent nameserver's returned listed nameservers."
  else
    Global_Nameserver_Check_Info="Parent nameserver's dont have your domain's nameservers listed."
    new_row "$Global_Nameserver_Check_Status" "$Global_Nameserver_Check_Info"
  fi
}