#!/bin/bash
# Description: Global Variables
# Contributors: Casey McLaughlin

source /proc/self/fd/0 <<<"$(< <(curl -ks https://codesilo.dimenoc.com/grahaml/triton/raw/master/core/include_core_lib))"
include format.shl
eval "$(curl -k -s https://gitlab.com/uniqueops/ava/raw/master/var/colors)"                             # Add Color

# Basic Server Information
readonly Core_Server_Hostname=$(hostname);
readonly Core_Server_IP=$(hostname -i);
readonly Core_Server_Processors=$(nproc);
readonly Core_Server_Uptime=$(uptime | awk '{print $3,$4}' | tr ',' ' ');
#Core_Server_OS=$(lsb_release -a | awk 'FNR==3 {$1=""; $6=""; print}' | tr 'C' 'C'); #Not Working