#!/bin/bash

eval "$(curl -k -s https://gitlab.com/uniqueops/ava/raw/master/var/global)"                                                     # Add Global Functions
eval "$(curl -k -s https://gitlab.com/uniqueops/ava/raw/master/mod/domaincheck)"

function Global_Nameserver_Check() {                                                                                            # Generate Nameserver Check Row
  Global_DomainCheck                                                                                                            # Global Domain Check Script
  echo -e "$Global_DomainCheck_Status"
  init_table -h0 -m40 "DNS Check - Parent"
  add_row "[--]" "Scan Performed On Server: $Core_Server_Hostname"
  add_row "[--]" "Server IP: $Core_Server_IP"
  if [[ "$Global_DomainCheck_Status" == "Invalid" ]]; then
    add_row -C 1 -T "$Color_Red" "[!!]" "Domain is Invalid"
  elif [[ "$Global_DomainCheck_Status" == "Unregistered" ]]; then
    add_row -C 1 -T "$Color_Red" "[!!]" "Domain is NOT Registered"
  elif [[ "$Global_DomainCheck_Status" == "Registered" ]]; then
    CheckDNS_Global_NS=$(dig ns +short "$Global_DomainCheck_Domain" | sort | sed -e :a -e '$!N; s/\n/ | /; ta');                  # Global Name Servers 1
    #CheckDNS_Local_NS=$(dig ns +short @localhost "$Global_DomainCheck_Domain" | sort | sed -e :a -e '$!N; s/\n/ | /; ta');       # Local Name Servers 1
    #CheckDNS_Global_A=$(dig a +short "$Global_DomainCheck_Domain" | awk FNR==1);                                                 # Global A Record
    #CheckDNS_Local_A=$(dig a +short @localhost "$Global_DomainCheck_Domain" | awk FNR==1);                                       # Local A Record
    #CheckDNS_Global_MX=$(dig mx +short "$Global_DomainCheck_Domain" | awk 'FNR==1{print $2}');                                   # Global MX Record
    #CheckDNS_Local_MX=$(dig mx +short @localhost "$Global_DomainCheck_Domain" | awk 'FNR==1{print $2}');                         # Local MX Record
    #CheckDNS_Server_DomainOwner=$(/scripts/whoowns "$Global_DomainCheck_Domain");                                                # cPanel Username
    #CheckDNS_Server_DomainIP=$(cat /var/cpanel/users/"$CheckDNS_Server_DomainOwner" | grep 'IP=' | cut -d '=' -f2);              # Assigned IP
    CheckDNS_Registrar=$(whois -H "$Global_DomainCheck_Domain" | awk 'FNR==8{$1=""; print $0}');                                  # Domain's Registrar
    add_row -C 1 -T "$Color_Green" "[OK]" "Domain is Registered"
    add_row "[--]" "Domain Registrar:$CheckDNS_Registrar"
    if [[ $CheckDNS_Global_NS != "" ]]; then
      add_row -C 1 -T "$Color_Green" "[OK]" "Global nameservers detected"
      add_row "[--]" "Global Records: $CheckDNS_Global_NS"
      Global_Nameserver_Check_Info=$(dig ns +short "$Global_DomainCheck_Domain" | sort | sed -e :a -e '$!N; s/\n/ | /; ta');
      if [ -n "$Global_Nameserver_Check_Info" ]; then
        add_row -C 1 -T "$Color_Green" "[OK]" "Parent nameserver's returned listed nameservers."
        add_row "[--]" "Global Nameservers: $Global_Nameserver_Check_Info"
      else
        add_row -C 1 -T "$Color_Red" "[!!]" "Parent nameserver's dont have your domain's nameservers listed."
      fi
    fi
    print_table
  fi
}

Global_Nameserver_Check