#!/bin/bash

## NOTES
# - Check into TLD Check with hostdime.co.uk
## END NOTES

eval "$(curl -k -s https://gitlab.com/uniqueops/ava/raw/master/var/global)"                                                         # Add Global Functions

function DNSCheck_Parent() {                                                                                                    # Generate Nameserver Check Row
  Global_DomainCheck                                                                                                            # Global Domain Check Script
  DNSCheck_A=$(dig +noall +answer "$Global_DomainCheck_Domain" | grep -v CNAME | awk '{print $NF}');
  DNSCheck_A_WWW=$(dig +noall +answer www."$Global_DomainCheck_Domain" | grep -v CNAME | awk '{print $NF}');
  DNSCheck_MX=$(dig +noall +answer mx "$Global_DomainCheck_Domain" | awk -F " " '{print $NF}' | sort);
  
  DNSCheck_GlobalServer=$(dig ns +short "$Global_DomainCheck_Domain_TLD" | head -1);
  DNSCheck_Registrar=$(whois -H "$Global_DomainCheck_Domain" | awk 'FNR==8{$1=""; print $0}');                                  # Domain's Registrar
  DNSCheck_NS=$(dig ns +short "$Global_DomainCheck_Domain" | sort | sed -e :a -e '$!N; s/\n/ | /; ta');  # Global Name Servers 1
  DNSCheck_NS_Compare=$(dig ns +short "$Global_DomainCheck_Domain" | sort)
  DNSCheck_NS_Count=$(dig ns +short "$Global_DomainCheck_Domain" | wc -l);  # Global Name Servers 1
  DNSCheck_NS_Glue=$(dig @"$DNSCheck_GlobalServer" +noall +additional "$Global_DomainCheck_Domain" | awk -F "A" '{print $NF}' | awk '{$1=$1}{ print}');
  DNSCheck_NS_Glue_Compare=$(dig @"$DNSCheck_GlobalServer" +noall +additional "$Global_DomainCheck_Domain" | awk -F " " '{print $1}' | awk '{$1=$1}{ print}' | sort);
  DNSCheck_NS_Glue_Count=$(echo "$DNSCheck_NS_Glue" | wc -l);

  init_table -h0 -m40 -f "DNS Check - Information"
  add_row "[--]" "Domain Checked: $Global_DomainCheck_Domain"
  add_row "[--]" "Domain Registrar:$DNSCheck_Registrar"
  add_row "[--]" "Parent Server: $DNSCheck_GlobalServer"
  print_table
  echo ""
  init_table -h0 -m40 -f "DNS Check - Parent"
  add_row "[--]" "Global Nameservers: $DNSCheck_NS"
  if [[ -n "$DNSCheck_GlobalServer" ]]; then
    add_row -C 1 -T "$Color_Green" "[OK]" "TLD Parent Check"
  else
    add_row -C 1 -T "$Color_Red" "[!!]" "Parent Nameservers Missing TLD Information"
  fi
  if [[ "$Global_DomainCheck_Status" == "Invalid" ]]; then
    add_row -C 1 -T "$Color_Red" "[!!]" "Domain is Invalid"
  elif [[ "$Global_DomainCheck_Status" == "Unregistered" ]]; then
    add_row -C 1 -T "$Color_Red" "[!!]" "Domain is NOT Registered"
  elif [[ "$Global_DomainCheck_Status" == "Registered" ]]; then
    add_row -C 1 -T "$Color_Green" "[OK]" "Domain Registered"
    if [[ $DNSCheck_NS != "" ]]; then
      if [ -n "$DNSCheck_NS" ]; then
        add_row -C 1 -T "$Color_Green" "[OK]" "Global Nameservers Returned"
      else
        add_row -C 1 -T "$Color_Red" "[!!]" "Global Nameservers Missing"
      fi
    fi
    if [[ -n "$DNSCheck_NS_Glue" ]]; then
      if [[ "$DNSCheck_NS_Compare" == "$DNSCheck_NS_Glue_Compare" ]]; then
        if [[ "$DNSCheck_NS_Count" == "$DNSCheck_NS_Glue_Count" ]]; then
          add_row -C 1 -T "$Color_Green" "[OK]" "Global Nameservers (A Records) Returned"
        else
          add_row -C 1 -T "$Color_Red" "[!!]" "Global Nameservers (Glue Records) Incomplete"
        fi
        add_row -C 1 -T "$Color_Green" "[OK]" "Global Nameservers (Glue Records) Returned"
      else
        add_row -C 1 -T "$Color_Yellow" "[??]" "Global Nameservers (Glue Records) Not All Returned"
      fi
    else
      add_row -C 1 -T "$Color_Red" "[!!]" "Global Nameservers Not Registered"
    fi      
  fi
  print_table

  # SOA Section
  DNSCheck_SOA_Check=$(dig +short soa "$Global_DomainCheck_Domain");
  DNSCheck_SOA_PrimaryNS=$(dig +short soa "$Global_DomainCheck_Domain" | awk -F " " '{print $1}');
  DNSCheck_SOA_Hostmaster=$(dig +short soa "$Global_DomainCheck_Domain" | awk -F " " '{print $2}');
  DNSCheck_SOA_Serial=$(dig +short soa "$Global_DomainCheck_Domain" | awk -F " " '{print $3}');
  DNSCheck_SOA_Refresh=$(dig +short soa "$Global_DomainCheck_Domain" | awk -F " " '{print $4}');
  DNSCheck_SOA_Retry=$(dig +short soa "$Global_DomainCheck_Domain" | awk -F " " '{print $5}');
  DNSCheck_SOA_Expire=$(dig +short soa "$Global_DomainCheck_Domain" | awk -F " " '{print $6}');
  DNSCheck_SOA_TTL=$(dig +short soa "$Global_DomainCheck_Domain" | awk -F " " '{print $7}');
  echo ""
  init_table -h0 -m40 -f "DNS Check - SOA"
  if [[ -n "$DNSCheck_SOA_Check" ]]; then
    add_row "[--]" "Primary Nameserver: $DNSCheck_SOA_PrimaryNS"
    add_row "[--]" "Hostmaster: $DNSCheck_SOA_Hostmaster"
    add_row "[--]" "Serial #: $DNSCheck_SOA_Serial"
    add_row "[--]" "Refresh: $DNSCheck_SOA_Refresh"
    add_row "[--]" "Retry: $DNSCheck_SOA_Retry"
    add_row "[--]" "Expire: $DNSCheck_SOA_Expire"
    add_row "[--]" "Default TTL: $DNSCheck_SOA_TTL"
    if [[ -n $(echo "$DNSCheck_NS" | grep "$DNSCheck_SOA_PrimaryNS") ]]; then
      add_row -C 1 -T "$Color_Green" "[OK]" "Primary Name Server Found In Your Global Nameservers"
    else
      add_row -C 1 -T "$Color_Yellow" "[??]" "Primary Name Server Not Found In Your Global Nameservers"
    fi
    if [[ "$DNSCheck_SOA_Refresh" != 86400 ]]; then
      add_row -C 1 -T "$Color_Green" "[OK]" "Refresh Interval Set to Recommended Value"
    else
      add_row -C 1 -T "$Color_Yellow" "[??]" "Refresh Interval Recommendation: 86400 Seconds (24 Hours)"
    fi    
    if [[ "$DNSCheck_SOA_Retry" == 7200 ]]; then
      add_row -C 1 -T "$Color_Green" "[OK]" "Retry Interval Set to Recommended Value"
    else
      add_row -C 1 -T "$Color_Yellow" "[??]" "Retry Interval Recommendation: 7200 Seconds (2 Hours)"
    fi
    if [[ "$DNSCheck_SOA_Retry" > "$DNSCheck_SOA_Refresh" ]]; then
      add_row -C 1 -T "$Color_Green" "[OK]" "Retry Interval Less Than Refresh Interval"
    else
      add_row -C 1 -T "$Color_Yellow" "[??]" "Retry Interval Recommended Less Than $DNSCheck_SOA_Refresh"
    fi
  else
    add_row -C 1 -T "$Color_Red" "Missing SOA Record"
  fi  
  print_table

  # MX Section
  echo ""
  init_table -h0 -m40 -f "DNS Check - MX"
  if [[ -n "$DNSCheck_MX" ]]; then
    #temp=$(echo -e "$DNSCheck_MX" | sed -e 's/^/add_row "[--]" "MX Record: /' | sed 's/.*/&"/')
    #echo $temp
    #while read DNSCheck_MX_Temp; do add_row "[--]" "MX Record: $DNSCheck_MX_Temp"; done
    add_row "[--]" "MX Record (Global): $DNSCheck_MX"
  else
    add_row -C 1 -T "$Color_Red" "Missing MX Record"
  fi  
  print_table

  # WWW Section
  echo ""
  init_table -h0 -m40 -f "DNS Check - WWW"
  if [[ -n "$DNSCheck_A_WWW" ]]; then
    add_row "[--]" "WWW A Record (Global): $DNSCheck_A_WWW"
    add_row -C 1 -T "$Color_Green" "[OK]" "Public IP Check"
    add_row -C 1 -T "$Color_Green" "[OK]" "CNAME Record Check"
  else
    add_row -C 1 -T "$Color_Red" "Missing WWW CNAME Record"
  fi
  print_table
  echo "";
}

DNSCheck_Parent
echo ""