#!/bin/bash
# Description: Domain DNS Health Checker
# Contributors: Casey McLaughlin

## Declare Local Settings ##
IFS="|";

## Local Variables ##







## Parent Table Fields ##

# Domain NS Records
Parent_NameServers=$(dig ns +short google.com | sed 's/.$//' | sort | sed -e :a -e '$!N; s/\n/|/; ta');
for ((i=0; i<${#Parent_NameServers[@]}; ++i)); do echo "${Parent_NameServers[$i]}"; done

# TLD Parent Check

# Nameservers Listed Check

# DNS Parent Glue Check

# Nameservers A Record Check