#!/bin/bash
# Description: Domain DNS Health Checker
# Contributors: Casey McLaughlin

## Local Variables ##
IFS="|";
Parent_NameServers="dig ns +short google.com | sed 's/.$//' | sort | sed -e :a -e '$!N; s/\n/|/; ta'";
Parent_NameServers_Array=($Parent_NameServers);
for ((i=0; i<${#Parent_NameServers_Array[@]}; ++i)); do echo "NameServer $i: ${Parent_NameServers_Array[$i]}"; done




## Parent Table Fields ##

# Domain NS Records

# TLD Parent Check

# Nameservers Listed Check

# DNS Parent Glue Check

# Nameservers A Record Check