#!/bin/bash

function Global_DomainCheck() { 

echo -e "\\nWhat is the domain?"                                                    # Ask For The Domain
read -r domain;                                                                     # Put Domain Into Variable

domain=$(echo "$domain" | tr '[:upper:]' '[:lower:]')                               # Convert All Characters to Lowercase
domain=$(echo "$domain" | sed 's/[^a-zA-Z0-9.:/]//g')                               # Remove Special Characters
domain=${domain#*//};                                                               # Remove Protocol Prefix
domain=${domain#*www.};                                                             # Remove WWW. Prefix
domain=$(echo "$domain" | cut -f1 -d"/")                                            # Remove Everything After TLD

if [ -z "$domain" ]; then
  Global_DomainCheck_Status="Invalid"
elif [ "whois $domain | grep 'No match for'" = "" ]; then
 echo -e "Test Worked!"
else
  Global_DomainCheck_Status="Valid"
fi

}

Global_DomainCheck
echo -e "$Global_DomainCheck_Status"