#!/bin/bash


#echo -e "\\nWhat is the domain?"                                                                                       # Ask For The Domain
#read -r domain;                                                                                                        # Put Domain Into Variable
domain="ht tps:// www . 123UNIQUEops.com !@#$%()^&* ~ -=_+ []{}\| ;: ,./<>? ' /test/ testing.php/"                           # All Special Characters Used Minus ` and "

echo -e "\\n\\n\\nStarted as: $domain\\n"                                                                               # Echo Domain For Testing Purposes                                                                                      # Declare Failing Status
domain=${domain//[[:blank:]]/}                                                                                          # Remove Spaces & Tabs
echo -e "Spaces Removed: $domain\\n"                                                                                    # Echo Domain For Testing Purposes                                                                                      # Declare Failing Status
domain=${domain#*//};                                                                                                   # Remove HTTP:// or HTTPS://
echo -e "http:// Removed: $domain\\n"                                                                                   # Echo Domain For Testing Purposes                                                                                      # Declare Failing Status
domain=${domain#*www.};                                                                                                 # Remove WWW.
echo -e "WWW Removed: $domain\\n"                                                                                       # Echo Domain For Testing Purposes                                                                                      # Declare Failing Status
domain=${domain%/};                                                                                                     # Remove Trailing /
echo -e "Trailing / Removed: $domain\\n"                                                                                # Echo Domain For Testing Purposes                                                                                      # Declare Failing Status

echo -e "$domain" | sed 's/[^a-zA-Z0-9.:/]//g' | tr '[:upper:]' '[:lower:]'

echo -e "\\n\\nFinal version is $domain\\n"                                                                                   # Echo Domain For Testing Purposes                                                                                      # Declare Failing Status


#cut -f1 -d":"

# tr '[:upper:]' '[:lower:]'