#!/bin/bash
# Description: Quick information for servers
# Contributors: Casey McLaughlin

# Initialize variables to default values.
OPT_V=V #Standard Flag for Output Mode
OPT_S=S #Standard Flag for Silent Mode
OPT_T=T #Standard Flag for Ticket Mode

# Help function
function HELP() {
  echo -e "\n$H1===================================$H2 Switches Template $H1===================================$RS\n";
  echo -e "Help documentation for ${BOLD}Switches Template.${RESET}"\\n
  echo -e "Command line switches are optional. The following switches are recognized."
  echo -e "${HIGHLIGHT}-c${RESET}  --Enables Checklist Mode: Print's in a quick format form"
  echo -e "${HIGHLIGHT}-n${RESET}  --Enables Noob Mode: Shows you what commands used."
  echo -e "${HIGHLIGHT}-o${RESET}  --Enables Output Mode: Displays standard output of a script."
  echo -e "${HIGHLIGHT}-s${RESET}  --Enables Silent Mode: Display only informative information."
  echo -e "${HIGHLIGHT}-t${RESET}  --Enables Ticket Mode: Displays output into a ticket format."
  echo -e "${HIGHLIGHT}-h${RESET}  --Displays this help message. No further functions performed."\\n
  echo -e "Example: ${BOLD}bash <(curl -ks https://codesilo.dimenoc.com/caseym/SSH-Scripts/raw/master/VersionChecker.sh) -h${RESET}"
  echo -e "\n$H1=========================================================================================$RS";
  exit 1
}

# Check the number of arguments. If none are passed, print help and exit.
NUMARGS=$#
if [ $NUMARGS -eq 0 ]; then
  HELP
fi

### Start getopts code ###

# Keep the leading ":" in front of flags 

while getopts ":cnosth" FLAG; do
  case "${FLAG}" in
    v)
      echo "You Picked v!"
      ;;
    s)
      echo "You Picked s!"
      ;;
    t)
      echo "You Picked t!"
      ;;
    h)
      HELP
      ;;
    \?) # Send to Help (Unrecognized Flag)
      HELP
      ;;
  esac
done

shift $((OPTIND-1))  #This tells getopts to move on to the next argument.

### End getopts code ###

exit 0