#!/bin/bash
# Description: Quick information for servers
# Contributors: Casey McLaughlin

echo -e "\n$Color_Blue====================$Color_Reset Uptime, Load Averages and Other Logged In Users $Color_Blue====================$Color_Reset\n";
w;
echo -e "\n$Color_Blue=========================================================================================$Color_Reset";
# Detect any screens and what is currently running in them
SCREEN=$(screen -ls 2>/dev/null | grep -v "No Sockets found in /var/run/screen/S-root."); 
INFO=$(ps faux | grep -v grep | grep -A2 "SCREEN" | egrep "SCREEN|_"); 
if [[ -n $INFO ]]; then echo -e "\n$Color_Blue========================================$Color_Reset Screens $Color_Blue========================================$Color_Reset\n $SCREEN \n$INFO \n$Color_Blue=========================================================================================$Color_Reset"; fi
;;
